name: "Sync Fork Branch 14.0"

on:
  schedule:
    - cron: '0 8 * * 4' # on Thursday at 8:00
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: OCA
          github_token: ${{ secrets.FORK_SYNC_TOKEN }}
          personal_token: ${{ secrets.FORK_SYNC_SIREKO_TOKEN }}
          base: "14.0"
          head: "14.0"
          merge_method: merge
          pr_title: "Fork Sync Branch 14.0"
          auto_approve: true
